# Generated by Django 4.1 on 2022-08-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_blog_options_blog_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
